import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Heading, Text } from '@chakra-ui/react';
import Button from '../components/Button';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Heading size={'title1'}>Title</Heading>
      <Heading size={'title2'}>Title</Heading>
      <Heading size={'title3'}>Title</Heading>
      <Heading size={'headline'}>Title</Heading>
      <Heading size={'subHeadline'}>Title</Heading>
      <Text textStyle={'body1Light'}>Title</Text>
      <Text textStyle={'body1Bold'}>Title</Text>
      <Text textStyle={'caption1'}>Title</Text>
      <Button type="primary" size="lg">
        text
      </Button>
    </div>
  );
};

export default Home;
