import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Box, Heading, StackDivider, VStack } from '@chakra-ui/react';
import Header from '../components/Header';
import TeacherCard from '../components/TeacherCard';
import { client } from '../libs/client';
import { Teacher } from '../types/api';
import VisibilitySection from '../components/VisibilitySection';

interface Props {
  teachers: Teacher[];
}

const Home: NextPage<Props> = ({ teachers }) => {
  console.log(teachers);
  return (
    <VisibilitySection chakraProps={{ mb: 10 }}>
      <Box className={styles.container}>
        <Head>
          <title>KnockLeran | 講師一覧</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header darkMode={false} />
        <Box as="main" className={styles.main}>
          <Heading size={'title1'} mb="48px">
            講師一覧
          </Heading>
          <VStack spacing={['48px', '40px']} divider={<StackDivider borderColor={'border'} />}>
            {teachers.map((teacher) => {
              return <TeacherCard key={teacher.id} content={teacher} />;
            })}
          </VStack>
        </Box>
      </Box>
    </VisibilitySection>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const data = await client.get({ endpoint: 'teacher' });
  return {
    props: {
      teachers: data.contents,
    },
  };
};
